name: Generate Arcade Graphs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # 1. Bikin gambar Ular pakai aturan V3 (Terbaru)
      - name: Generate Snake Graph 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: Blank-MC
          outputs: |
            dist/snake-dark.svg?palette=github-dark

      # 2. Bikin gambar Pacman pakai aturan V2 (Jadul)
      - name: Generate Pacman Graph 🍒
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Blank-MC
          svg_out_path: dist/pacman-dark.svg

      # 3. Upload dua-duanya ke branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
